services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    cpus: 0.25
    mem_limit: 256m
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${SHOWS_DIR}:/shows
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    cpus: 0.25
    mem_limit: 256m
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MOVIES_DIR}:/movies
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    cpus: 0.25
    mem_limit: 256m
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/lidarr:/config
      - ${MUSIC_DIR}:/music
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - "8686:8686"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    cpus: 0.25
    mem_limit: 256m
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    cpus: 0.25
    mem_limit: 256m
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/jellyseerr:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    cpus: 0.25
    mem_limit: 256m
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    ports:
      - "8191:8191"
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cpus: 0.25
    mem_limit: 512m
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - OPENVPN_PASSWORD=${NORD_PASS}
      - OPENVPN_USER=${NORD_USER}
      - SERVER_CATEGORIES=p2p
      - SERVER_COUNTRIES=${VPN_COUNTRY}
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=nordvpn
    volumes:
      - ${CONFIG_DIR}/gluetun:/gluetun
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "8880:8880"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    cpus: 0.5
    mem_limit: 512m
    depends_on:
      - gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8880
    network_mode: "service:gluetun"
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DOWNLOADS_DIR}:/downloads
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    cpus: 0.125
    mem_limit: 128m
    depends_on:
      - sonarr
      - radarr
      - lidarr
      - prowlarr
      - jellyseerr
      - qbittorrent
      - emby
    volumes:
      - ${CONFIG_DIR}/cloudflared:/etc/cloudflared:ro
    command: tunnel run
    networks:
      - default
      - seafile
    restart: unless-stopped

  emby:
    image: emby/embyserver:latest
    container_name: emby
    cpus: 1
    mem_limit: 2g
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]    
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/emby/config:/config
      - ${CONFIG_DIR}/emby/logs:/logs
      - ${SHOWS_DIR}:/media/shows
      - ${MOVIES_DIR}:/media/movies
      - ${MUSIC_DIR}:/media/music
      - ${UPLOAD_LOCATION}/upload:/media/immich
    ports:
      - "8096:8096"
      - "8920:8920"
    restart: unless-stopped

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    cpus: 0.5
    mem_limit: 512m
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - seafile
    restart: unless-stopped

  memcached:
    image: memcached:1.6-alpine
    container_name: seafile-memcached
    cpus: 0.125
    mem_limit: 128m
    entrypoint: memcached -m 128
    networks:
      - seafile
    restart: unless-stopped

  seafile:
    image: seafileltd/seafile-mc:11.0-latest
    container_name: seafile
    cpus: 0.5
    mem_limit: 512m
    expose:
      - "80"
    environment:
      - DB_HOST=mariadb
      - DB_ROOT_PASSWD=${MYSQL_ROOT_PASSWORD}
      - SERVICE_URL=https://seafile.${SERVER_HOSTNAME}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
      - SEAFILE_SERVER_HOSTNAME=seafile.${SERVER_HOSTNAME}
      - SEAFILE_SERVER_LETSENCRYPT=${SEAFILE_SERVER_LETSENCRYPT}
      - TIME_ZONE=${TZ}
    tmpfs:
      - /opt/seafile/pids
    volumes:
      - seafile-data:/shared
    depends_on:
      - mariadb
      - memcached
    networks:
      - seafile
    restart: unless-stopped

  postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0@sha256:fa4f6e0971f454cd95fec5a9aaed2ed93d8f46725cc6bc61e0698e97dba96da1
    container_name: postgres
    cpus: 0.5
    mem_limit: 512m
    environment:
      - DB_STORAGE_TYPE=HDD
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - immich-postgres-data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - database
    restart: always

  redis:
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    container_name: redis
    cpus: 0.125
    mem_limit: 128m
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    restart: always

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: immich_machine_learning
    cpus: 1
    mem_limit: 512m
    env_file:
      - .env
    volumes:
      - immich-redis-data:/cache
    restart: always
    healthcheck:
      disable: false

  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich_server
    cpus: 1
    mem_limit: 2g
    env_file:
      - .env
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - postgres
    restart: always
    healthcheck:
      disable: false

networks:
  default:
    driver: bridge
  seafile:
    driver: bridge

volumes:
  seafile-data:
  mariadb-data:
  immich-redis-data:
  immich-postgres-data: