services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    cpus: 0.5
    mem_limit: 512m    
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${SHOWS_DIR}:/shows
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    cpus: 0.5
    mem_limit: 512m    
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MOVIES_DIR}:/movies
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    cpus: 0.5
    mem_limit: 512m    
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/lidarr:/config
      - ${MUSIC_DIR}:/music
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - "8686:8686"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    cpus: 0.5
    mem_limit: 512m    
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    cpus: 0.5
    mem_limit: 512m    
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/jellyseerr:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    cpus: 0.5
    mem_limit: 512m    
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    ports:
      - "8191:8191"
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cpus: 0.5
    mem_limit: 1g    
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${NORD_USER}
      - OPENVPN_PASSWORD=${NORD_PASS}
      - SERVER_CATEGORIES=p2p
      - SERVER_COUNTRIES=${VPN_COUNTRY}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/gluetun:/gluetun
    ports:
      - "8880:8880"
      - "6881:6881/tcp"
      - "6881:6881/udp"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    cpus: 1
    mem_limit: 1g    
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8880
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DOWNLOADS_DIR}:/downloads
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    cpus: 0.25
    mem_limit: 256m    
    depends_on:
      - emby
      - sonarr
      - radarr
      - lidarr
      - prowlarr
      - jellyseerr
      - qbittorrent
    volumes:
      - ${CONFIG_DIR}/cloudflared:/etc/cloudflared:ro
    command: tunnel run
    networks:
      - default
      - seafile
    restart: unless-stopped

  emby:
    image: emby/embyserver:latest
    container_name: emby
    cpus: 2
    mem_limit: 4g
    runtime: nvidia
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "8096:8096"
      - "8920:8920"      
    volumes:
      - ${CONFIG_DIR}/emby/config:/config
      - ${CONFIG_DIR}/emby/logs:/logs
      - ${SHOWS_DIR}:/media/shows
      - ${MOVIES_DIR}:/media/movies
      - ${MUSIC_DIR}:/media/music   
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    cpus: 1
    mem_limit: 1g    
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - seafile
    restart: unless-stopped

  memcached:
    image: memcached:1.6-alpine
    container_name: seafile-memcached
    cpus: 0.25
    mem_limit: 256m    
    entrypoint: memcached -m 256
    networks:
      - seafile
    restart: unless-stopped

  seafile:
    image: seafileltd/seafile-mc:11.0-latest
    container_name: seafile
    cpus: 1
    mem_limit: 1g    
    expose:
      - "80"
    environment:
      - DB_HOST=mariadb
      - DB_ROOT_PASSWD=${MYSQL_ROOT_PASSWORD}
      - TIME_ZONE=${TZ}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
      - SEAFILE_SERVER_LETSENCRYPT=${SEAFILE_SERVER_LETSENCRYPT}
      - SEAFILE_SERVER_HOSTNAME=seafile.${SERVER_HOSTNAME}
      - SERVICE_URL=https://seafile.${SERVER_HOSTNAME}
    volumes:
      - seafile-data:/shared
    tmpfs:
      - /opt/seafile/pids
    depends_on:
      - mariadb
      - memcached
    networks:
      - seafile
    restart: unless-stopped

networks:
  default:
    driver: bridge
  seafile:
    driver: bridge

volumes:
  seafile-data:
  mariadb-data: