services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    cpus: 0.5
    mem_limit: 512m
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${CONFIG_DIR}/sonarr:/config:cached"
      - "${SHOWS_DIR}:/shows:cached"
      - "${DOWNLOADS_DIR}:/downloads:cached"
    ports:
      - "8989:8989"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    cpus: 0.5
    mem_limit: 512m
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${CONFIG_DIR}/radarr:/config:cached"
      - "${MOVIES_DIR}:/movies:cached"
      - "${DOWNLOADS_DIR}:/downloads:cached"
    ports:
      - "7878:7878"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    cpus: 0.5
    mem_limit: 512m
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${CONFIG_DIR}/lidarr:/config:cached"
      - "${MUSIC_DIR}:/music:cached"
      - "${DOWNLOADS_DIR}:/downloads:cached"
    ports:
      - "8686:8686"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    cpus: 0.5
    mem_limit: 512m
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${CONFIG_DIR}/prowlarr:/config:cached"
    ports:
      - "9696:9696"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    cpus: 0.5
    mem_limit: 1g
    environment:
      LOG_LEVEL: "info"
      TZ: "${TZ}"
    volumes:
      - "${CONFIG_DIR}/jellyseerr:/app/config:cached"
    ports:
      - "5055:5055"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    cpus: 0.5
    mem_limit: 512m
    environment:
      LOG_LEVEL: "info"
      TZ: "${TZ}"
    ports:
      - "8191:8191"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cpus: 0.5
    mem_limit: 512m
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      OPENVPN_USER: "${NORD_USER}"
      OPENVPN_PASSWORD: "${NORD_PASS}"
      SERVER_CATEGORIES: p2p
      SERVER_COUNTRIES: "${VPN_COUNTRY}"
      TZ: "${TZ}"
      VPN_SERVICE_PROVIDER: nordvpn
    volumes:
      - "${CONFIG_DIR}/gluetun:/gluetun:cached"
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "8880:8880"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    cpus: 0.5
    mem_limit: 1g
    depends_on:
      - gluetun
    network_mode: service:gluetun
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      WEBUI_PORT: 8880
    volumes:
      - "${CONFIG_DIR}/qbittorrent:/config:cached"
      - "${DOWNLOADS_DIR}:/downloads:cached"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    cpus: 0.25
    mem_limit: 512m
    depends_on:
      - sonarr
      - radarr
      - lidarr
      - prowlarr
      - jellyseerr
      - qbittorrent      
      - emby
      - immich-server
    volumes:
      - "${CONFIG_DIR}/cloudflared:/etc/cloudflared:ro"
    command: tunnel run
    networks:
      - default
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"        

  emby:
    image: emby/embyserver:latest
    container_name: emby
    cpus: 3.0
    mem_limit: 3g
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    volumes:
      - "${CONFIG_DIR}/emby/config:/config:cached"
      - "${CONFIG_DIR}/emby/logs:/logs:cached"
      - "${SHOWS_DIR}:/media/shows:cached"
      - "${MOVIES_DIR}:/media/movies:cached"
      - "${MUSIC_DIR}:/media/music:cached"
      - "${IMMICH_DIR}/upload:/media/immich:cached"
    ports:
      - "8096:8096"
      - "8920:8920"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"

  postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    container_name: postgres
    cpus: 0.5
    mem_limit: 1g
    environment:
      DB_STORAGE_TYPE: HDD
      POSTGRES_DB: "${DB_DATABASE_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - immich-postgres-data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - database
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"

  redis:
    image: docker.io/valkey/valkey:8-bookworm
    container_name: redis
    cpus: 0.25
    mem_limit: 256m
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: immich_machine_learning
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    cpus: 2.0
    mem_limit: 4g
    env_file:
      - .env
    volumes:
      - immich-redis-data:/cache
    restart: always
    healthcheck:
      disable: false
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"

  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich_server
    runtime: nvidia
    cpus: 2.5
    mem_limit: 4g
    env_file:
      - .env
    volumes:
      - "${IMMICH_DIR}:/usr/src/app/upload:cached"
      - "${UPLOADS_DIR}:/uploads:cached"
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - postgres
    restart: always
    healthcheck:
      disable: false
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    cpus: 0.25
    mem_limit: 256m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "${CONFIG_DIR}/dozzle:/data:cached"
    environment:
      DOZZLE_AUTH_PROVIDER: simple
    expose:
      - "8080"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - "${CONFIG_DIR}/plex:/config"
      - "${SHOWS_DIR}:/data/tv"
      - "${MOVIES_DIR}:/data/movies"
      - "${MUSIC_DIR}:/data/music"
      - "${DOWNLOADS_DIR}:/data/downloads"
      - "${CONFIG_DIR}/plex/transcode:/transcode"
    ports:
      - "32400:32400"
      - "32469:32469"
      - "1900:1900/udp"
      - "5353:5353/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    network_mode: 'host'
    volumes:
      - /path/to/config:/config
      - /path/to/cache:/cache
      - type: bind
        source: /path/to/media
        target: /media
      - type: bind
        source: /path/to/media2
        target: /media2
        read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      - type: bind
        source: /path/to/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  default:
    driver: bridge

volumes:
  immich-redis-data:
  immich-postgres-data: